name: Package for Windows
description: Create Windows packages for Launcher

inputs:
  version:
    description: Launcher version
    required: true
  build-type:
    description: Type for the build
    required: true
    default: Debug
  artifact-name:
    description: Name of the uploaded artifact
    required: true
  msystem:
    description: MSYS2 subsystem to use
    required: false

runs:
  using: composite

  steps:
    - name: Package (MinGW)
      if: ${{ inputs.msystem != '' }}
      shell: bash
      env:
        BUILD_DIR: build
        INSTALL_DIR: install
      run: |
        cmake --install "$BUILD_DIR" --config "${{ inputs.build-type }}"
        touch "$INSTALL_DIR/manifest.txt"
        for l in $(find "$INSTALL_DIR" -type f); do
          l=$(cygpath -u "$l")
          l="${l#$(pwd)/}"
          l="${l#$INSTALL_DIR/}"
          l="${l#./}"
          echo "$l"
        done >> "$INSTALL_DIR/manifest.txt"

    - name: Package (MSVC)
      if: ${{ inputs.msystem == '' }}
      shell: pwsh
      env:
        BUILD_DIR: build
        INSTALL_DIR: install
      run: |
        cmake --install "$env:BUILD_DIR" --config "${{ inputs.build-type }}"

        cd "${{ github.workspace }}"

        Get-ChildItem "$env:INSTALL_DIR" -Recurse |
          ForEach-Object { $_.FullName } |
          Resolve-Path -Relative |
          ForEach-Object { $_.TrimStart('.\').TrimStart("$env:INSTALL_DIR").TrimStart('\') } |
          Out-File -FilePath "$env:INSTALL_DIR/manifest.txt"

    - name: Package (MinGW, portable)
      if: ${{ inputs.msystem != '' }}
      shell: bash
      env:
        BUILD_DIR: build
        INSTALL_DIR: install
        INSTALL_PORTABLE_DIR: install-portable
      run: |
        cp -r "$INSTALL_DIR" "$INSTALL_PORTABLE_DIR"
        cmake --install "$BUILD_DIR" --config "${{ inputs.build-type }}" --prefix "$INSTALL_PORTABLE_DIR" --component portable
        for l in $(find "$INSTALL_PORTABLE_DIR" -type f); do
          l=$(cygpath -u "$l")
          l="${l#$(pwd)/}"
          l="${l#$INSTALL_PORTABLE_DIR/}"
          l="${l#./}"
          echo "$l"
        done >> "$INSTALL_PORTABLE_DIR/manifest.txt"

    - name: Package (MSVC, portable)
      if: ${{ inputs.msystem == '' }}
      shell: pwsh
      env:
        BUILD_DIR: build
        INSTALL_DIR: install
        INSTALL_PORTABLE_DIR: install-portable
      run: |
        Copy-Item -Recurse "$env:INSTALL_DIR" "$env:INSTALL_PORTABLE_DIR"
        cmake --install "$env:BUILD_DIR" --config "${{ inputs.build-type }}" --prefix "$env:INSTALL_PORTABLE_DIR" --component portable

        Get-ChildItem "$env:INSTALL_PORTABLE_DIR" -Recurse |
          ForEach-Object { $_.FullName } |
          Resolve-Path -Relative |
          ForEach-Object { $_.TrimStart('.\').TrimStart("$env:INSTALL_PORTABLE_DIR").TrimStart('\') } |
          Out-File -FilePath "$env:INSTALL_PORTABLE_DIR/manifest.txt"

    - name: Package (installer)
      shell: pwsh
      env:
        BUILD_DIR: build
        INSTALL_DIR: install
        NSCURL_VERSION: "v24.9.26.122"
        NSCURL_SHA256: "AEE6C4BE3CB6455858E9C1EE4B3AFE0DB9960FA03FE99CCDEDC28390D57CCBB0"
      run: |
        New-Item -Name NSISPlugins -ItemType Directory -Force
        Invoke-WebRequest "https://github.com/negrutiu/nsis-nscurl/releases/download/${{ env.NSCURL_VERSION }}/NScurl.zip" -OutFile "NSISPlugins/NScurl.zip"
        $hash = Get-FileHash "NSISPlugins/NScurl.zip" -Algorithm Sha256 | Select-Object -ExpandProperty Hash
        if ($hash -ne "${{ env.NSCURL_SHA256 }}") {
          Write-Error "NSCurl.zip sha256 mismatch"
          exit 1
        }
        Expand-Archive -Path "NSISPlugins/NScurl.zip" -DestinationPath "NSISPlugins/NScurl"

        cd "${{ github.workspace }}/${{ env.INSTALL_DIR }}"
        makensis -NOCD "${{ github.workspace }}/${{ env.BUILD_DIR }}/program_info/win_install.nsi"

    - name: Upload binary zip
      uses: actions/upload-artifact@v7
      with:
        name: Launcher-${{ inputs.artifact-name }}-${{ inputs.version }}-${{ inputs.build-type }}
        path: install/**

    - name: Upload portable zip
      uses: actions/upload-artifact@v7
      with:
        name: Launcher-${{ inputs.artifact-name }}-Portable-${{ inputs.version }}-${{ inputs.build-type }}
        path: install-portable/**

    - name: Upload installer
      uses: actions/upload-artifact@v7
      with:
        name: Launcher-${{ inputs.artifact-name }}-Setup-${{ inputs.version }}-${{ inputs.build-type }}
        path: Launcher-Setup.exe
