version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels:
      - "area: actions"
      - "type: robot"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels:
      - "area: dependencies"
      - "type: robot"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    labels:
      - "area: dependencies"
      - "type: robot"
