# ParseLauncherConfig.cmake
# Reads res/launcher-config.yaml and sets Launcher_* variables.

function(parse_launcher_config)
    set(_config_file "${CMAKE_SOURCE_DIR}/res/launcher-config.yaml")
    if(NOT EXISTS "${_config_file}")
        message(WARNING "Launcher config not found: ${_config_file}")
        return()
    endif()

    file(READ "${_config_file}" _content)
    string(REPLACE "\n" ";" _lines "${_content}")

    set(_current_section "")
    foreach(_line IN LISTS _lines)
        string(REGEX REPLACE "^[ \t]+" "" _line "${_line}")
        string(REGEX REPLACE "[ \t]+$" "" _line "${_line}")

        if("${_line}" STREQUAL "" OR "${_line}" MATCHES "^#")
            continue()
        endif()

        if("${_line}" MATCHES "^([a-zA-Z_]+):[ \t]*$")
            set(_current_section "${CMAKE_MATCH_1}")
            continue()
        endif()

        if("${_line}" MATCHES "^([a-zA-Z_]+):[ \t]+(.+)$")
            set(_key "${CMAKE_MATCH_1}")
            set(_value "${CMAKE_MATCH_2}")
            string(REGEX REPLACE "^['\"]|['\"]$" "" _value "${_value}")

            if(NOT "${_current_section}" STREQUAL "")
                set(_yaml_${_current_section}_${_key} "${_value}")
            else()
                set(_yaml_${_key} "${_value}")
            endif()
            continue()
        endif()

        if("${_line}" MATCHES "^([a-zA-Z_]+):$")
            set(_key "${CMAKE_MATCH_1}")
            if(NOT "${_current_section}" STREQUAL "")
                set(_yaml_${_current_section}_${_key} "")
            else()
                set(_yaml_${_key} "")
            endif()
            continue()
        endif()
    endforeach()

    # Map parsed values to Launcher_* in parent scope
    # Use DEFINED checks to handle zero/empty values correctly

    if(DEFINED _yaml_app_name AND NOT _yaml_app_name STREQUAL "")
        set(Launcher_CommonName "${_yaml_app_name}" PARENT_SCOPE)
        set(Launcher_DisplayName "${_yaml_app_name}" PARENT_SCOPE)
        set(Launcher_Name "${_yaml_app_name}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_app_app_id AND NOT _yaml_app_app_id STREQUAL "")
        set(Launcher_AppID "${_yaml_app_app_id}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_app_domain AND NOT _yaml_app_domain STREQUAL "")
        set(Launcher_Domain "${_yaml_app_domain}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_app_git_url AND NOT _yaml_app_git_url STREQUAL "")
        set(Launcher_Git "${_yaml_app_git_url}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_app_binary_name AND NOT _yaml_app_binary_name STREQUAL "")
        set(Launcher_APP_BINARY_NAME "${_yaml_app_binary_name}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_version_major)
        set(Launcher_VERSION_MAJOR "${_yaml_version_major}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_version_minor)
        set(Launcher_VERSION_MINOR "${_yaml_version_minor}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_version_patch)
        set(Launcher_VERSION_PATCH "${_yaml_version_patch}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_urls_news_rss AND NOT _yaml_urls_news_rss STREQUAL "")
        set(Launcher_NEWS_RSS_URL "${_yaml_urls_news_rss}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_news_open AND NOT _yaml_urls_news_open STREQUAL "")
        set(Launcher_NEWS_OPEN_URL "${_yaml_urls_news_open}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_wiki AND NOT _yaml_urls_wiki STREQUAL "")
        set(Launcher_WIKI_URL "${_yaml_urls_wiki}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_help AND NOT _yaml_urls_help STREQUAL "")
        set(Launcher_HELP_URL "${_yaml_urls_help}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_login_callback AND NOT _yaml_urls_login_callback STREQUAL "")
        set(Launcher_LOGIN_CALLBACK_URL "${_yaml_urls_login_callback}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_legacy_fmllibs AND NOT _yaml_urls_legacy_fmllibs STREQUAL "")
        set(Launcher_LEGACY_FMLLIBS_BASE_URL "${_yaml_urls_legacy_fmllibs}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_meta AND NOT _yaml_urls_meta STREQUAL "")
        set(Launcher_META_URL "${_yaml_urls_meta}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_bug_tracker AND NOT _yaml_urls_bug_tracker STREQUAL "")
        set(Launcher_BUG_TRACKER_URL "${_yaml_urls_bug_tracker}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_translations AND NOT _yaml_urls_translations STREQUAL "")
        set(Launcher_TRANSLATIONS_URL "${_yaml_urls_translations}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_translation_files AND NOT _yaml_urls_translation_files STREQUAL "")
        set(Launcher_TRANSLATION_FILES_URL "${_yaml_urls_translation_files}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_discord AND NOT _yaml_urls_discord STREQUAL "")
        set(Launcher_DISCORD_URL "${_yaml_urls_discord}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_urls_imgur_client_id AND NOT _yaml_urls_imgur_client_id STREQUAL "")
        set(Launcher_IMGUR_CLIENT_ID "${_yaml_urls_imgur_client_id}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_updater_github_repo AND NOT _yaml_updater_github_repo STREQUAL "")
        set(Launcher_UPDATER_GITHUB_REPO "${_yaml_updater_github_repo}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_copyright_label AND NOT _yaml_copyright_label STREQUAL "")
        set(Launcher_Authors "${_yaml_copyright_label}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_copyright_text AND NOT _yaml_copyright_text STREQUAL "")
        set(Launcher_Copyright "${_yaml_copyright_text}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_copyright_mac AND NOT _yaml_copyright_mac STREQUAL "")
        set(Launcher_Copyright_Mac "${_yaml_copyright_mac}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_native_glfw_library AND NOT _yaml_native_glfw_library STREQUAL "")
        set(Launcher_GLFW_LIBRARY_NAME "${_yaml_native_glfw_library}" PARENT_SCOPE)
    endif()
    if(DEFINED _yaml_native_openal_library AND NOT _yaml_native_openal_library STREQUAL "")
        set(Launcher_OPENAL_LIBRARY_NAME "${_yaml_native_openal_library}" PARENT_SCOPE)
    endif()

    if(DEFINED _yaml_build_qt_version_major AND NOT _yaml_build_qt_version_major STREQUAL "")
        set(Launcher_QT_VERSION_MAJOR "${_yaml_build_qt_version_major}" PARENT_SCOPE)
    endif()

    message(STATUS "Loaded launcher config from ${_config_file}")
endfunction()
