name: cleanlauncher
base: core22
version: '111.0.x'
summary: CleanLauncher
description: |
  CleanLauncher is a C++/Rust launcher application.

grade: stable
confinement: strict

parts:
  launcher:
    plugin: cmake
    source: .
    build-packages:
      - build-essential
      - qt6-base-dev
      - extra-cmake-modules
      - pkg-config
      - scdoc
      - libcmark-dev
      - libarchive-dev
      - libqrencode-dev
      - zlib1g-dev
      - libxcb-cursor-dev
      - libtomlplusplus-dev
      - libgl1-mesa-dev
      - libglvnd-dev
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6

apps:
  launcher:
    command: bin/launcher
    extensions: [kde-neon]
