name: Clang-Tidy Code Scanning

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  pull_request:

permissions: {}

jobs:
  clang-tidy:
    name: Run Clang-Tidy

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Run source generators
        run: |
          nix develop --command bash -c '
            cmake -B build -D Launcher_USE_PCH=OFF && cmake --build build --target autogen autorcc
          '

      - name: Run clang-tidy-diff
        env:
          BASE_REF: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
        run: |
          nix develop --command bash -c '
            clang-tidy -verify-config && git diff -U0 --no-color "$BASE_REF" | clang-tidy-diff.py -p1 -quiet -only-check-in-db
          '
