name: Clang-Tidy Code Scanning

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  pull_request:

permissions: {}

jobs:
  clang-tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: "true"

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install cmake ninja-build extra-cmake-modules pkg-config \
            qt6-base-dev qt6-base-dev-tools qt6-svg-dev \
            libgl1-mesa-dev libglu1-mesa-dev libglvnd-dev \
            libxcb-cursor-dev libtomlplusplus-dev \
            libcmark-dev libarchive-dev libqrencode-dev zlib1g-dev \
            libxkbcommon-dev qt6-networkauth-dev

      - name: Run source generators
        run: |
          cmake -B build -D Launcher_USE_PCH=OFF && cmake --build build --target autogen autorcc

      - name: Run clang-tidy-diff
        env:
          BASE_REF: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
        run: |
          clang-tidy -verify-config && git diff -U0 --no-color "$BASE_REF" | clang-tidy-diff.py -p1 -quiet -only-check-in-db
