name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "master"
      - "develop"
      - "release-*"
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Test (${{ matrix.artifact-name }})

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            artifact-name: Linux
            cmake-preset: linux
            qt-version: 6.10.2

          - os: macos-26
            artifact-name: macOS
            cmake-preset: macos_universal
            macosx-deployment-target: 12.0
            qt-version: 6.9.3

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env:
      BUILD_TYPE: Debug
      CMAKE_PRESET: ${{ matrix.cmake-preset }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macosx-deployment-target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          build-type: ${{ env.BUILD_TYPE }}
          artifact-name: ${{ matrix.artifact-name }}
          qt-version: ${{ matrix.qt-version }}

      - name: Configure project
        run: |
          cmake --preset "$CMAKE_PRESET"

      - name: Run build
        run: |
          cmake --build --preset "$CMAKE_PRESET" --config "$BUILD_TYPE"

      - name: Run tests
        run: |
          ctest --preset "$CMAKE_PRESET" --build-config "$BUILD_TYPE" --output-on-failure
